### ISSUE TITLE
Why style the raw page?

### ISSUE THREAD

**Issue by PragmaticEd** [StylishThemes/GitHub-Dark-Script#12]
```
// @include      /raw\.githubusercontent\.com/
```

Any reason for this?
In my case, i have JsonFormatter plugin. And i don't need the style..

I realize i can fork and change it, but i was wondering, why You use the theme on raw page..

**Comment by silverwind** [comment]
> Any reason for this?

It's a personal preference of mine to not have a bright "flash" when viewing raw files. With this being the script, I could see an option being added that does an early exit from the script if `document.location.hostname === "raw.githubusercontent.com"`.

**Comment by Mottie** [comment]
I also prefer a darker background on raw pages.

If you really hate it, add a custom Stylish theme:

``` css
@-moz-document domain("githubusercontent.com") {
  body {
    background: #fff !important;
  }
}
```
