### ISSUE TITLE
(GitHub Toggle Code Wrap) Inline file action button and context-menu cut

### ISSUE THREAD

**Issue by jerone** [StylishThemes/GitHub-Dark-Script#66]
The inline file action button and context-menu is cut: 

![image](https://user-images.githubusercontent.com/55841/60755529-48461d00-9ff1-11e9-834e-eb482a085e48.png)

Correct (with "GitHub Toggle Code Wrap" disabled):

![image](https://user-images.githubusercontent.com/55841/60755544-79bee880-9ff1-11e9-816c-19ca1e56f482.png)

See it in action here:
https://github.com/StylishThemes/GitHub-Dark-Script/blob/master/github-script-code-wrap.user.js#L203

That is also the offending line of code, causing this issue.

**Comment by Mottie** [comment]
Hi @jerone!

Hmm, yeah that's going to be a difficult fix. The file action button and the code table are siblings. If we add the following to remove the `overflow` setting on the wrapper:

```css
.ghd-code-wrapper {
  overflow: unset !important;
}
.ghd-wrap-table {
  overflow-x: auto !important;
}
```

It looks okay until you toggle the wrap

![](https://user-images.githubusercontent.com/136959/60757182-c7752a00-9fcc-11e9-90c6-24336e42bc4c.gif)

Another alternative would be to move the block to the right, but then it overlaps the line number.

```css
.BlobToolbar {
  left: 2px !important;
}
```

![](https://user-images.githubusercontent.com/136959/60757222-44080880-9fcd-11e9-82f9-5a8bf2b953c1.png)

What do you think? cc: @silverwind @the-j0k3r
